export const DEFAULT_CHART_ACCOUNTS = [
  { code: '1', name: 'Activo', type: 'activo', parentCode: null },
  { code: '1.1', name: 'Caja y Bancos', type: 'activo', parentCode: '1' },
  { code: '1.2', name: 'Créditos por ventas', type: 'activo', parentCode: '1' },
  { code: '1.3', name: 'Bienes de cambio', type: 'activo', parentCode: '1' },
  { code: '2', name: 'Pasivo', type: 'pasivo', parentCode: null },
  { code: '2.1', name: 'Deudas comerciales', type: 'pasivo', parentCode: '2' },
  { code: '2.2', name: 'IVA débito fiscal', type: 'pasivo', parentCode: '2' },
  { code: '2.3', name: 'IVA crédito fiscal', type: 'pasivo', parentCode: '2' },
  { code: '3', name: 'Patrimonio Neto', type: 'patrimonio', parentCode: null },
  { code: '3.1', name: 'Capital', type: 'patrimonio', parentCode: '3' },
  { code: '3.2', name: 'Resultados acumulados', type: 'patrimonio', parentCode: '3' },
  { code: '4', name: 'Ingresos', type: 'ingreso', parentCode: null },
  { code: '4.1', name: 'Ventas', type: 'ingreso', parentCode: '4' },
  { code: '4.2', name: 'Otros ingresos', type: 'ingreso', parentCode: '4' },
  { code: '5', name: 'Egresos', type: 'egreso', parentCode: null },
  { code: '5.1', name: 'Costo de mercadería', type: 'egreso', parentCode: '5' },
  { code: '5.2', name: 'Gastos administrativos', type: 'egreso', parentCode: '5' },
  { code: '5.3', name: 'Gastos comerciales', type: 'egreso', parentCode: '5' },
] as const;
